# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-05 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('joining_date', models.DateField()),
                ('role', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Employee_id', to='leavemanagement.Employee')),
                ('Manager_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Manager_id', to='leavemanagement.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days', models.IntegerField()),
                ('status', models.CharField(max_length=200)),
                ('Emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Emp_id', to='leavemanagement.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Leave_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('max_days', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='leave',
            name='leave_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_type_id', to='leavemanagement.Leave_type'),
        ),
    ]
