# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-14 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leavemanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='days',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
