# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-17 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leavemanagement', '0002_leave_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_relation',
            name='Employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Employee_id', to='leavemanagement.Employee'),
        ),
        migrations.AlterField(
            model_name='employee_relation',
            name='Manager_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Manager_id', to='leavemanagement.Employee'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='Emp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Emp_id', to='leavemanagement.Employee'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_type_id', to='leavemanagement.Leave_type'),
        ),
    ]
